### ISSUE TITLE
Study isn’t clear on how the results are generalisable to the population

### ISSUE THREAD

**Issue by Sealjay** [carstenmaple/SpeakForYourself#1]
The study results have an excellent overview of how the population sampled were representative of the U.K. population as a whole, however the results don’t appear to be generalisable to the whole population.

If the results cannot be generalised, I’m not clear how they allow the paper to achieve one of the stated aims “[to allow] governments to make appropriate design choices to ensure adequate uptake and participation.”

While researchers may understand the distinction between a representative study, and the ability to generalise to the whole population, the [secondary reporting is already confusing the two](https://medicalxpress.com/news/2020-05-uk-nhs-body-covid-contact-tracing.html), assuming that this report is sufficient to make sweeping statements about the whole of the U.K. general public.

**Comment by carstenmaple** [comment]
Thanks so much for the interest in the work and a useful comment.  Of course, we are well aware of the issues of population sampling and generalising across a population.  Without surveying the whole population, sampling is the only viable method.  Indeed, "Population-based survey experiments are experimental designs embedded within surveys that are “administered to a representative population sample” (Mutz 2011, 2; see also Nock and Guterbock 2010, 860). They have become an ostensible “gold standard” for generalizable causal inferences. ” [Mullinix, Kevin J., Thomas J. Leeper, James N. Druckman, and Jeremy Freese. "The generalizability of survey experiments." Journal of Experimental Political Science 2, no. 2 (2015): 109-138.]

We have, as you recognise, been representative across many attributes and believe this significantly moves the understanding forward from the very rudimentary and non-representative surveys that have preceded.

Thanks again for a useful comment
